// Generated by apps/api/scripts/export-openapi.mjs from the API source. Do not edit: run `npm run openapi -w @bitocard/api`.

/** Every scope an API key can hold (`apiKeyScopes` in the API). */
export const apiKeyScopes = [
  'catalogue:read',
  'quotes:write',
  'orders:read',
  'orders:write',
  'wallet:read',
  'wallet:write',
  'webhooks:manage',
  'events:read',
  'stores:manage',
  'customers:verify',
] as const;

/** Event types an endpoint can subscribe to (`eventTypes` in the API); `*` means all, including later ones. */
export const webhookEventTypes = [
  'order.completed',
  'order.failed',
  'order.refunded',
  'top_up.succeeded',
  'top_up.failed',
  'payout.paid',
  'payout.failed',
  'customer_verification.approved',
  'customer_verification.declined',
  'number.renewed',
  'number.expired',
  'number.deleted',
  'number.sms_received',
] as const;
