import Image from "next/image";
import { brand } from "./site";

/**
 * The Bitocard logo: the "b" mark on the left, then the name "Bitocard" ("Bito" navy, "card" pink). Each app serves
 * the mark from its own public/ folder (generated by scripts/brand-assets.py). Needs .brand-icon, .brand-name and
 * .brand-accent from @bitocard/ui/styles (workspace.css or brand-lockup.css).
 */
export function Brand() {
  return (
    <>
      <span className="brand-icon" aria-hidden="true">
        <Image src={brand.mark} alt="" width={378} height={512} sizes="64px" priority />
      </span>
      <span className="brand-name">
        Bito<span className="brand-accent">card</span>
      </span>
    </>
  );
}
