import Image from "next/image";
import { brand } from "./site";

/**
 * The BitoCard wordmark: the "b" mark is the first letter, followed by "ito" and a pink "Card". Each app serves the
 * mark from its own public/ folder (generated by scripts/brand-assets.py). Read as one word, "BitoCard".
 * Needs .brand-name, .brand-b and .brand-accent from @bitocard/ui/styles (workspace.css or brand-lockup.css).
 */
export function Brand() {
  return (
    <span className="brand-name" role="img" aria-label={brand.name}>
      <span className="brand-b" aria-hidden="true">
        <Image src={brand.mark} alt="" width={380} height={512} sizes="64px" priority />
      </span>
      <span aria-hidden="true">ito</span>
      <span className="brand-accent" aria-hidden="true">Card</span>
    </span>
  );
}
