import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { ImageResponse } from "next/og";

/**
 * Square favicon / app icon: the "b" mark (public/bitocard-mark.png, generated by scripts/brand-assets.py) centred
 * in the square, filling `fill` of its height. Use from an app's icon.tsx or apple-icon.tsx; give iOS home-screen
 * icons a background and a smaller fill so the mark has room around it.
 */
export async function brandIcon(size: number, { fill = 0.92, background = "transparent" }: { fill?: number; background?: string } = {}) {
  const mark = await readFile(join(process.cwd(), "public/bitocard-mark.png"));
  const src = `data:image/png;base64,${mark.toString("base64")}`;
  const height = Math.round(size * fill);
  const width = Math.round((height * 380) / 512);

  return new ImageResponse(
    (
      <div style={{ width: "100%", height: "100%", display: "flex", alignItems: "center", justifyContent: "center", background }}>
        {/* eslint-disable-next-line @next/next/no-img-element -- ImageResponse renders plain img elements */}
        <img src={src} alt="" width={width} height={height} />
      </div>
    ),
    { width: size, height: size },
  );
}
