// Writes the API description to openapi.json (committed, so docs and reviews see every change), and the API's lists
// that SHQ needs (API key scopes, webhook event types) to packages/api-client/src/reseller/api-lists.generated.ts, so the
// dashboard never keeps its own copy. Run after `npm run build`. `--check` fails if either committed file is out of date.
import { readFileSync, writeFileSync } from 'node:fs';
import { createApp, buildOpenApi } from '../dist/bootstrap.js';
import { apiKeyScopes } from '../dist/api-keys/api-keys.service.js';
import { eventTypes } from '../dist/webhooks/events.js';

const app = await createApp();
app.useLogger(false);
await app.init();
const json = `${JSON.stringify(buildOpenApi(app), null, 2)}\n`;
await app.close();

const list = values => `[\n${values.map(value => `  '${value}',`).join('\n')}\n] as const`;
const lists = `// Generated by apps/api/scripts/export-openapi.mjs from the API source. Do not edit: run \`npm run openapi -w @bitocard/api\`.

/** Every scope an API key can hold (\`apiKeyScopes\` in the API). */
export const apiKeyScopes = ${list(apiKeyScopes)};

/** Event types an endpoint can subscribe to (\`eventTypes\` in the API); \`*\` means all, including later ones. */
export const webhookEventTypes = ${list(eventTypes)};
`;

const outputs = [
  { file: new URL('../openapi.json', import.meta.url), name: 'openapi.json', content: json },
  { file: new URL('../../../packages/api-client/src/reseller/api-lists.generated.ts', import.meta.url), name: 'api-lists.generated.ts', content: lists },
];

if (process.argv.includes('--check')) {
  const stale = outputs.filter(({ file, content }) => {
    try {
      return readFileSync(file, 'utf8').replace(/\r\n/g, '\n') !== content;
    } catch {
      return true;
    }
  });
  if (stale.length) {
    console.error(`${stale.map(output => output.name).join(' and ')} out of date. Run \`npm run openapi -w @bitocard/api\` and commit the result.`);
    process.exit(1);
  }
  console.log('openapi.json and api-lists.generated.ts are up to date.');
} else {
  for (const { file, name, content } of outputs) {
    writeFileSync(file, content);
    console.log(`Wrote ${name}`);
  }
}
